### ISSUE TITLE
Add Pet

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#10]
Staff can add a new pet to an existing client with pet name, species, gender, and date of birth.

**Comment by BekahT** [comment]
- Redirects to Clients tab, find client, and then add pet.
- Species dropdown (cat, dog, guinea pig, fish, rabbit, ferret, etc.)
- Gender dropdown
- DOB use datepicker
- DOB must be in the past. Cannot be in the future.

**Comment by BekahT** [comment]
Pet test data for Angela: https://theoffice.fandom.com/wiki/Angela%27s_cats

**Comment by BekahT** [comment]
- [x] There's a maskformatter on petdob, but it's not displaying/auto-formatting as you type. It should show the dashes and auto-format for the user.
- I shortened some error messages so they would fit in the window. We should either make the window wider, or keep our errors short.
- [x] The buttons for Submit and Cancel have black text, while the Add client ones have blue text. Pick a color and use it for all submit/cancel buttons.

**Comment by cp-umuc** [comment]
I don't like saying click the paw button - sounds weird.  The User Guide should explain that it is the Add Pet button so we should call it that. If you want to keep the paw part then maybe "Paw icon" or something?
<img width="418" alt="Screen Shot 2020-04-23 at 9 39 39 PM" src="https://user-images.githubusercontent.com/62041224/80166365-c046f900-85ab-11ea-9029-43723e91023b.png">

**Comment by cp-umuc** [comment]
After we add a new pet, we should be returned to the Pets dashboard instead of the Clients dashboard. I know you mentioned returning to the Clients dashboard when canceling the Add Pet and that's fine - like in case they clicked on the wrong client - but if they are successful they should be taken to the Pets dashboard with the updated Pet list.

**Comment by cp-umuc** [comment]
No page heading on the Add Pet page like is seen on the Add Client Page.
<img width="145" alt="Screen Shot 2020-04-23 at 10 31 08 PM" src="https://user-images.githubusercontent.com/62041224/80168970-377f8b80-85b2-11ea-8f80-c5e8cca6ca6e.png">

**Comment by cp-umuc** [comment]
Invalid pet name results in error message going off the screen.
<img width="370" alt="Screen Shot 2020-04-23 at 10 37 08 PM" src="https://user-images.githubusercontent.com/62041224/80169287-0ce20280-85b3-11ea-9418-4f2824b46836.png">

**Comment by cp-umuc** [comment]
Same cut off for date of birth in the future error.
<img width="386" alt="Screen Shot 2020-04-23 at 10 43 03 PM" src="https://user-images.githubusercontent.com/62041224/80169591-e07ab600-85b3-11ea-857e-56d6268fa63c.png">

**Comment by cp-umuc** [comment]
No error message displayed for empty date of birth. (Nothing happens when you click Submit.)
<img width="376" alt="Screen Shot 2020-04-23 at 10 44 48 PM" src="https://user-images.githubusercontent.com/62041224/80169666-16b83580-85b4-11ea-9a70-28bd7ecc33c5.png">

**Comment by BekahT** [comment]
I resolved the no error on empty dob one, in my update to the edit pet merge request.

**Comment by BekahT** [comment]
> I don't like saying click the paw button - sounds weird. The User Guide should explain that it is the Add Pet button so we should call it that. If you want to keep the paw part then maybe "Paw icon" or something?
> <img alt="Screen Shot 2020-04-23 at 9 39 39 PM" width="418" src="https://user-images.githubusercontent.com/62041224/80166365-c046f900-85ab-11ea-9029-43723e91023b.png">

Maybe something like "Please select a client and click the Add Pet button (paw icon) to create a new pet."

**Comment by BekahT** [comment]
Shrink error font to match size used in Add Client.

**Comment by BekahT** [comment]
- Changed all warnings to font size 14 from 18 (also matches add client warning fields). Updated Edit Pet as well.
- Updated Add Pet Instructions message.
- Added title to Add Pet window.
- Redirect client to pets tab upon successful pet creation
