### ISSUE TITLE
Edit Pet

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#12]
Staff can edit an existing pet’s name, species, gender, and date of birth.

**Comment by BekahT** [comment]
- Popup window with same form as Add Pet, but with pet info pre-filled. 
- Cannot edit client. Show as read-only.

**Comment by BekahT** [comment]
- Need to revisit the validation on DOB in the Edit form. Right now we allow them to be empty and submitted with just the formatting. If a pet is edited to have a blank dob, edit and delete on them breaks. I was able to fix this in the add form using a regex, but for some reason it's not applying during the edit.

**Comment by BekahT** [comment]
Submit and Cancel buttons need to be consistent with others in application. See Add Pet or Add / Edit client buttons (blue text).

**Comment by BekahT** [comment]
Shrink error font to match size used in Edit Client.

**Comment by BekahT** [comment]
> Shrink error font to match size used in Edit Client.

Resolved in bug fixes for Add Pet. Changed to font size 14 from 18.

**Comment by BekahT** [comment]
> * Need to revisit the validation on DOB in the Edit form. Right now we allow them to be empty and submitted with just the formatting. If a pet is edited to have a blank dob, edit and delete on them breaks. I was able to fix this in the add form using a regex, but for some reason it's not applying during the edit.

- Resolved by uncommenting a line of code formatting the dob field.

**Comment by BekahT** [comment]
- Resolved all bugs currently listed.

**Comment by cp-umuc** [comment]
I can still edit a pet to have a date of birth in the future and the error message for empty date of birth field is different than for create pet ("All fields are required" vs "DOB must be in yyyy-mm-dd format!").

**Comment by brease568** [comment]
Fixed the bug allowing a user to edit a pet's DOB into the future. I'm confused on your comment on the empty date of birth error message. If the date of birth field is left empty the error message should be "All fields are required." That seems right. The error message "DOB must be in yyyy-mm-dd" message should only be thrown if there is an invalid date (not including one in the future). I might have fixed this by adding missing return statements to two date validity checks that were added?

**Comment by cp-umuc** [comment]
It doesn't matter which error message we use - I just get two different error messages when I leave the DOB field empty in edit vs create and I think it should be consistent. Can you not reproduce the error messages being different in the two for empty fields?

Add - empty DOB
<img width="461" alt="Screen Shot 2020-04-25 at 11 20 49 AM" src="https://user-images.githubusercontent.com/62041224/80283617-f046e700-86e6-11ea-8d12-c0062a5ac3e5.png">

Edit - empty DOB
<img width="473" alt="Screen Shot 2020-04-25 at 11 21 18 AM" src="https://user-images.githubusercontent.com/62041224/80283620-f5a43180-86e6-11ea-952c-05bf8e36f279.png">

Looks like in Edit I can remove the dashes but in Add I can.  Is the formatting being enforced differently?
