### ISSUE TITLE
Search Pets

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#15]
Staff can search for an existing pet.

**Comment by BekahT** [comment]
- Search by pet name or client last name only.

**Comment by cp-umuc** [comment]
Functionality appears to work.
1) Can we add some of the default data for SQL including at least two pets with the same name for my test case write up (want the prof to be able to run any test cases using existing data)?
2) This search has the same issue as the Client search where the criteria is saved even after the user leaves the tab.  We should clear the search criteria when we go to a different dashboard.
3) Do we want to have a No Results Found message if there are no matches to the search criteria?

**Comment by cp-umuc** [comment]
Are we going to keep the date of birth search criteria?  It wasn't included in the original plan so I'll need to add a test case for it if we are  - just let me know.

**Comment by BekahT** [comment]
1. Added data.
2. **There don't seem to be event listeners for switching tabs. Need to investigate further.**
3. Added no results message. Dialogue says no results and table is not changed. 
4. Removed dob search field and updated references in code.
