### ISSUE TITLE
Create Appointment

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#16]
Staff can create a new appointment for an existing client and pet combination with an appointment reason, date, and time.

**Comment by BekahT** [comment]
- Clicking Create Appointment re-directs to Pets page. Search for pet, then click Create Appointment in pet table.
- Open new window with new appointment form.

**Comment by BekahT** [comment]
- Pet and owner automatically filled in based on which pet was selected for the appointment

**Comment by BekahT** [comment]
- Validate dates (or use a date picker)
- Validate all fields are not empty
- Validate appointment is not at a date in the past
- Validate that appointment is not at the same time/date as an existing appointment (b/c date/time combo is PK)

**Comment by BekahT** [comment]
##### From the design doc:
When a user wants to create an appointment, they are redirected from the Appointments Dashboard to the Pets Dashboard. There, they select the pet for which the appointment is being made. After clicking “Create Appointment” on the selected pet, the user will be redirected to the “Create Appointment” page.
	The user will be required to enter a date, time, and reason for the appointment. The clients and pets fields will be pre-populated with the linked client and pet data; this information cannot be modified. The entered information must be in a valid format. Fields that are left empty and fields that have invalid characters will trigger an error message. This error message will detail the user’s mistake. The user can modify their input and submit again. Additionally, an appointment cannot be made in the past. Attempting to create an appointment in the past will result in an error being displayed to the user. If valid data has been submitted, the date and time will be checked against the dates and times of other appointments listed in the database. The user will not be allowed to create an appointment if one already exists with the selected date and time. An error will be displayed to the user if they attempt to create an appointment with a conflicting date and time. If at any time, the user wishes to stop creating an appointment, they have the option to select “Cancel”. This will redirect them to the Appointments Dashboard, and no changes will be made.

**Comment by BekahT** [comment]
### Date and Time Pickers
- 3rd party library (new dependency jar) https://github.com/LGoodDatePicker/LGoodDatePicker/releases
- https://github.com/LGoodDatePicker/LGoodDatePicker
- Download and run LGoodDatePicker-10.4.1-executable-demo.jar to see examples.
- In the example, I think the DateTimePicker 2, Disallow Empty date and times is what we want.
- This is the code for that demo in the jar https://github.com/LGoodDatePicker/LGoodDatePicker/blob/master/Project/src/main/java/com/github/lgooddatepicker/demo/FullDemo.java

**Comment by cp-umuc** [comment]
This should say "cancel to return to Pets Dashboard".
<img width="520" alt="Screen Shot 2020-04-29 at 9 21 06 AM" src="https://user-images.githubusercontent.com/62041224/80600812-f1378b80-89fa-11ea-868b-b21ec7419b57.png">

**Comment by cp-umuc** [comment]
I can create appointments in the past if I use today's date but a time from earlier today. (ex: it is 9am but I can make an appointment for today at 7am.)

**Comment by cp-umuc** [comment]
Error message for creating appointment with same date/time gets cut off.
<img width="521" alt="Screen Shot 2020-04-29 at 9 54 12 AM" src="https://user-images.githubusercontent.com/62041224/80604228-7755d100-89ff-11ea-881a-31b11ce35031.png">
Wording of the error message seems weird too - Maybe "Another appointment is scheduled for that date/time. Try again."?

**Comment by BekahT** [comment]
Resolved Crystal's comments on #104

**Comment by cp-umuc** [comment]
Can now add appointments at the same date/time without an error. (two appointments on 05-05 at 12:00)
<img width="478" alt="Screen Shot 2020-04-29 at 11 49 43 AM" src="https://user-images.githubusercontent.com/62041224/80617260-e0dddb80-8a0f-11ea-8b12-969fd5c630fb.png">

**Comment by BekahT** [comment]
The duplicate error appears if the duplicate appointments are for today. So I think the date in the datetime is defaulting to today. In the insertAppointment() method in Database.java, we need to create the datetime from the provided date and time. Right now we're just inserting the time directly, which I believe makes the date portion of the datetime today.

**Comment by BekahT** [comment]
- Duplicate bug resolved in #106 
- I updated the appts in the db so they all use the new method. Any old ones will have the wrong date in the datetime, so they may still appear to allow duplicates.
