### ISSUE TITLE
Edit Appointment

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#18]
Staff can edit an existing   appointment’s reason, date, or time.

**Comment by BekahT** [comment]
- Popup new window with same form as Create Appointment, but fields are filled in and editable, EXCEPT for client and pet, which cannot be edited.
- Pass appointment object from the row that was clicked to populate the form.
- Validate dates (or use a date picker)
- Validate all fields are not empty
- Validate appointment is not at a date in the past
- Validate that appointment is not at the same time/date as an existing appointment (b/c date/time combo is PK)

**Comment by cp-umuc** [comment]
Error message when editing an appointment to have the same date/time as an existing appointment.
<img width="500" alt="Screen Shot 2020-04-30 at 9 43 46 AM" src="https://user-images.githubusercontent.com/62041224/80717731-34f7c700-8ac7-11ea-8173-e98e3db856b6.png">
Error message should be more descriptive and match what it is in create appointment - "Appointment date/time is already taken!"

**Comment by BekahT** [comment]
The insert appointment catch for errors has an if to return the duplicate error when a certain error is returned and the generic unable to create otherwise. The edit appointment catch didn't have the if statement for the dup error, so I added that.
