### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#2]
Staff can log into the application with a username and password.

**Comment by BekahT** [comment]
Meeting notes:
- On unsuccessful login, say "invalid credentials" or something that does not specifically indicate which part of the credentials were invalid.
- Red text under login form, not a popup box.
- Reset the form on invalid login.

**Comment by cp-umuc** [comment]
Need to agree on default log in creds and document themm.

**Comment by cp-umuc** [comment]
Login button is blank
<img width="804" alt="Screen Shot 2020-04-16 at 7 12 22 AM" src="https://user-images.githubusercontent.com/62041224/79449725-bfadd180-7fb1-11ea-828b-87fa34fb3ab7.png">

**Comment by cp-umuc** [comment]
Exit button is missing.

**Comment by cp-umuc** [comment]
Error messages about empty or invalid creds needs to be displayed as red text on the GUI, not in the console.

**Comment by cp-umuc** [comment]
Error message for "Username or password can not be empty!" - cannot is one word

**Comment by cp-umuc** [comment]
Error in console with valid username/invalid password:
Invalid username or password!

Error in console with invalid username/invalid password:
Authentication unsuccessful: ResultSet closed
Invalid username or password!

**Comment by BekahT** [comment]
Exit button does not exit the application.
Suggested default credentials "Staff" and "P@ssw0rd"

**Comment by BekahT** [comment]
#### Already done previously
- [x] On unsuccessful login, say "invalid credentials" or something that does not specifically indicate which part of the credentials were invalid.
- [x] Red text under login form, not a popup box.
- [x] Login button text is blank
- [x] Exit button is missing
- [x] Error messages about empty or invalid creds needs to be displayed as red text on the GUI, not in the console.
- [x] Error in console with valid username/invalid password: Invalid username or password!
- [x] Error in console with invalid username/invalid password: Authentication unsuccessful: ResultSet closed Invalid username or password!
#### Issues Addressed
- [x] Exit button does not exit the application
- [x] Reset the form on invalid login.
#### Issues Not Addressed (going in separate ticket)
- [ ] Need to agree on default log in creds and document them
- [ ] Suggested default credentials "Staff" and "P@ssw0rd"

**Comment by cp-umuc** [comment]
Username should be case insensitive - BOB/bob/Bob, whatever as long as the password is right.

**Comment by BekahT** [comment]
Made username case insensitive in https://github.com/BekahT/VetApp/pull/43
