### ISSUE TITLE
Audit Log - Pet Actions

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#26]
The Application shall log actions taken on pet records, including creation, edit, and delete.

NIST Audit Event Content Recommendations:
https://nvd.nist.gov/800-53/Rev4/control/AU-3

**Comment by cp-umuc** [comment]
Audit messages for add/delete pet are inconsistent with data displayed. (Edit isn't implemented yet so I can't check it.)
<img width="986" alt="Screen Shot 2020-04-23 at 9 58 52 PM" src="https://user-images.githubusercontent.com/62041224/80167185-bb834480-85ad-11ea-87d4-feae2c2026e9.png">

**Comment by BekahT** [comment]
Updated delete to include dob. Checked that edit already contains the same info.
