### ISSUE TITLE
Add client

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#4]
Staff can add a new client with first name, last name, phone number, and email address.

**Comment by BekahT** [comment]
- Validate all fields are not blank
- Validate field formats / valid characters

**Comment by cp-umuc** [comment]
Trying to put something invalid in the create client window causes a pop up window instead of a red error message to appear and when you close the pop up the entire create client window disappears so the user has to start over.  Should be a red error message and user stays on the same page.
<img width="775" alt="Screen Shot 2020-04-16 at 7 20 12 AM" src="https://user-images.githubusercontent.com/62041224/79450622-1a93f880-7fb3-11ea-9f89-731ae5a01a4e.png">

**Comment by cp-umuc** [comment]
What are the invalid character list we are using? I feel like this should be okay...
<img width="831" alt="Screen Shot 2020-04-16 at 7 23 58 AM" src="https://user-images.githubusercontent.com/62041224/79450751-516a0e80-7fb3-11ea-953b-5467cb50d313.png">

**Comment by cp-umuc** [comment]
There isn't validation on the phone number and formatting isn't present
<img width="528" alt="Screen Shot 2020-04-16 at 7 28 42 AM" src="https://user-images.githubusercontent.com/62041224/79451109-013f7c00-7fb4-11ea-8944-4076c53da056.png">

**Comment by BekahT** [comment]
- Clicking Cancel should close the Add Client form. Currently, clicking it does nothing.
- Add a window title (like the main one is Vet Portal) of "Add Client". Then remove the large "Add Client" in the window body and replace it with something like "Complete the below form to add a new client" (in regular size text).

**Comment by cp-umuc** [comment]
Clicking submit with missing fields doesn't result in same type of error message as invalid field values (in console instead)

**Comment by nour-d** [comment]
> Trying to put something invalid in the create client window causes a pop up window instead of a red error message to appear and when you close the pop up the entire create client window disappears so the user has to start over. Should be a red error message and user stays on the same page.
> <img alt="Screen Shot 2020-04-16 at 7 20 12 AM" width="775" src="https://user-images.githubusercontent.com/62041224/79450622-1a93f880-7fb3-11ea-9f89-731ae5a01a4e.png">

Just fixed both issues in features-new branch

**Comment by BekahT** [comment]
#### Already done
- [x] Staff can add a new client with first name, last name, phone number, and email address.
- [x] Validate all fields are not blank
- [x] Validate field formats / valid characters
- [x] Trying to put something invalid in the create client window causes a pop up window instead of a red error message to appear and when you close the pop up the entire create client window disappears so the user has to start over. Should be a red error message and user stays on the same page.
- [x] There isn't validation on the phone number and formatting isn't present
- [x] Clicking submit with missing fields doesn't result in same type of error message as invalid field values (in console instead)

#### Added by me
- [x] What are the invalid character list we are using? Should allow apostrophe, hyphen, and alphabetical characters. (didn't allow spaces)
- [x] Clicking Cancel should close the Add Client form. Currently, clicking it does nothing.
- [x] Add a window title (like the main one is Vet Portal) of "Add Client". Then remove the large "Add Client" in the window body and replace it with something like "Complete the below form to add a new client" (in regular size text).
- [x] first and last name format error gets cut off in window (reduced font size and widened area)
- [x] shorten db error on duplicate phone number so it doesn't get cut off
- [x] When submitted with blank/invalid fields, display error, but don't reset the whole form

**Comment by cp-umuc** [comment]
Phone number validation is still not right - I can submit an empty phone number and when an invalid number is entered (less than 10 numbers) an incorrect error message is displayed.
<img width="467" alt="Screen Shot 2020-04-17 at 8 21 26 PM" src="https://user-images.githubusercontent.com/62041224/79623233-18cc5100-80e9-11ea-9fcc-804d7f18f0be.png">

**Comment by BekahT** [comment]
Resolved phone number validation in https://github.com/BekahT/VetApp/pull/44
