### ISSUE TITLE
Update Design Document

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#68]
- Update design document to match current implementation and note changes in the Phase II report
- Review dashboard tables
- Review search criteria
- Review fields being shown in create pages
- Review fields being shown in edit pages

**Comment by cp-umuc** [comment]
These are the things I remember us discussing for changes...
Changes from this Phase:
- Species is editable
- No DOB search field on Pets dashboard

Changes for next Phase:
- Remove search by time

**Comment by cp-umuc** [comment]
Commented on Updated Design Doc
