### ISSUE TITLE
Make application wider

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#80]
- Make all pages of the application wider (maybe by 50%?). 
- Make error messages in add / edit windows a smaller font than the rest of the text so longer messages will fit.

**Comment by cp-umuc** [comment]
Log in page
<img width="710" alt="Screen Shot 2020-04-24 at 2 17 36 PM" src="https://user-images.githubusercontent.com/62041224/80244343-c3d39200-8636-11ea-895e-d9cbb9394692.png">

Appointments dashboard
<img width="700" alt="Screen Shot 2020-04-24 at 2 17 53 PM" src="https://user-images.githubusercontent.com/62041224/80244369-cf26bd80-8636-11ea-9125-2dca46ce0f68.png">

Pets dashboard
<img width="698" alt="Screen Shot 2020-04-24 at 2 18 03 PM" src="https://user-images.githubusercontent.com/62041224/80244388-d5b53500-8636-11ea-8e1e-466d3fcb6fd8.png">

Clients dashboard
<img width="698" alt="Screen Shot 2020-04-24 at 2 18 13 PM" src="https://user-images.githubusercontent.com/62041224/80244409-dbab1600-8636-11ea-8e45-a33aae9b10fa.png">

Create Client
<img width="550" alt="Screen Shot 2020-04-24 at 2 18 31 PM" src="https://user-images.githubusercontent.com/62041224/80244436-e36aba80-8636-11ea-9cc7-4abd91f8a8a4.png">

Edit Client
<img width="548" alt="Screen Shot 2020-04-24 at 2 18 48 PM" src="https://user-images.githubusercontent.com/62041224/80244446-e8c80500-8636-11ea-91d1-4fcc36b5f0b5.png">

Delete Client
<img width="428" alt="Screen Shot 2020-04-24 at 2 19 48 PM" src="https://user-images.githubusercontent.com/62041224/80244463-efef1300-8636-11ea-92a8-1af308de1b3c.png">

Create Pet 
<img width="518" alt="Screen Shot 2020-04-24 at 2 19 05 PM" src="https://user-images.githubusercontent.com/62041224/80244480-f7aeb780-8636-11ea-826f-2e5c10264fab.png">

Edit Pet
<img width="548" alt="Screen Shot 2020-04-24 at 2 19 21 PM" src="https://user-images.githubusercontent.com/62041224/80244492-fd0c0200-8636-11ea-84cd-1ce85bf29dcb.png">

Delete Pet
<img width="381" alt="Screen Shot 2020-04-24 at 2 19 59 PM" src="https://user-images.githubusercontent.com/62041224/80244508-039a7980-8637-11ea-9899-35a398b404f4.png">

Search - no results
<img width="331" alt="Screen Shot 2020-04-24 at 2 20 15 PM" src="https://user-images.githubusercontent.com/62041224/80244534-0d23e180-8637-11ea-9f6d-c768f0e800b5.png">

**Comment by cp-umuc** [comment]
Create Pet with invalid name
<img width="517" alt="Screen Shot 2020-04-24 at 2 24 51 PM" src="https://user-images.githubusercontent.com/62041224/80244725-6f7ce200-8637-11ea-9e52-85f017907842.png">

Create Pet with empty date
<img width="515" alt="Screen Shot 2020-04-24 at 2 52 53 PM" src="https://user-images.githubusercontent.com/62041224/80247004-5aa24d80-863b-11ea-877f-7c1b56fb387c.png">

Create Pet with invalid date
<img width="517" alt="Screen Shot 2020-04-24 at 2 25 45 PM" src="https://user-images.githubusercontent.com/62041224/80244795-95a28200-8637-11ea-9f18-99804c46f859.png">

Edit Pet with invalid name
<img width="546" alt="Screen Shot 2020-04-24 at 2 26 56 PM" src="https://user-images.githubusercontent.com/62041224/80244864-b8349b00-8637-11ea-8c16-aab55dd5e79d.png">

Phone number cut off on Client dashboard search
<img width="695" alt="Screen Shot 2020-04-24 at 2 39 28 PM" src="https://user-images.githubusercontent.com/62041224/80245897-83294800-8639-11ea-84be-138edf298578.png">

**Comment by cp-umuc** [comment]
Client error message for comparison
<img width="547" alt="Screen Shot 2020-04-24 at 2 58 06 PM" src="https://user-images.githubusercontent.com/62041224/80247469-16637d00-863c-11ea-82bb-4557bbcfc289.png">
