### ISSUE TITLE
Search Clients

### ISSUE THREAD

**Issue by BekahT** [BekahT/VetApp#9]
Staff can search for an existing client.

**Comment by BekahT** [comment]
- Put the phone validation/formatter on the phone search field
- Make searches case insensitive

**Comment by BekahT** [comment]
- Search/filter the local array list instead of going back to the db
- See https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html
- https://stackoverflow.com/a/37743809

**Comment by BekahT** [comment]
https://github.com/BekahT/VetApp/tree/searchClients

**Comment by cp-umuc** [comment]
Please don't move to testing until there is a jar for me to test.

**Comment by cp-umuc** [comment]
The phone number gets cut off in the search - we're okay with that right?
<img width="161" alt="Screen Shot 2020-04-23 at 9 26 05 PM" src="https://user-images.githubusercontent.com/62041224/80165264-21210200-85a9-11ea-9b07-ceb095d3f266.png">

**Comment by cp-umuc** [comment]
For testing purposes of the multiple criteria search - can we add two clients with the same last name to the default SQL data (so I can search on last name and email but only the right one is displayed)?  Maybe Dwight and Mose Schrute to fit with the Office theme? Obviously I can add data for my local testing but I'd prefer that the prof be able to run any of the test cases we submit off of default data.

**Comment by cp-umuc** [comment]
The test case states that an informational message will be displayed if no matches are found (like No Results displayed in the table instead of data?).  Do we want to implement this or should I remove that expectation from the test cases? (it isn't a separate test case but a note on the other search ones so it would be easy to remove if we want to go that route)

**Comment by cp-umuc** [comment]
Search data should clear after leaving the tab.  Right now if I click to the Pets tab and click Create Pet I'm brought back to the Clients dashboard with only the results of my last search displayed instead of all Clients as I would expect.

**Comment by BekahT** [comment]
Phone number doesn't get cut off in my view, but I do think we need to make the application wider overall. 
![image](https://user-images.githubusercontent.com/29181959/80206393-35d9b600-85fa-11ea-9d4c-8408cd54e785.png)
I'll address the rest of the feedback this evening.

**Comment by BekahT** [comment]
- For test data, added Mose Schrute (same last name as Dwight Schrute) and Jim's parents Gerald and Betsy Halpert, and Pam's parents Helene and William. Note that Helene and William also share an email address.
- Added two animals with the same name Rosie, with different species, genders, dob, and owners.
- Several owners have more than one pet.

**Comment by BekahT** [comment]
- When no results are found, a popup dialogue appears notifying the user and the table is not changed.

**Comment by BekahT** [comment]
- Still need to address "Search data should clear after leaving the tab. Right now if I click to the Pets tab and click Create Pet I'm brought back to the Clients dashboard with only the results of my last search displayed instead of all Clients as I would expect." 
- There don't seem to be action listeners for switching tabs. I need to look into this more.
